name: Minecraft2Arduino
author: tetelie
main: fr.tetelie.Minecraft2Arduino
version: 0.1 dev
commands:
  minecraft2arduino:
    description: nan
    usage: /m2a help
    permission: minecraft2arduino.command
    aliases:
      - m2a